-- MySQL Script generated by MySQL Workbench
-- Fri Oct 21 23:09:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LaVie
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LaVie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LaVie` DEFAULT CHARACTER SET utf8 ;
USE `LaVie` ;

-- -----------------------------------------------------
-- Table `LaVie`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LaVie`.`pacientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `idade` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LaVie`.`psicologo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LaVie`.`psicologo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `apresentacao` VARCHAR(45) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LaVie`.`atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LaVie`.`atendimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_atendimento` VARCHAR(45) NOT NULL,
  `observacao` TEXT NOT NULL,
  `id_psicologo` INT NOT NULL,
  `id_pacientes` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  INDEX `fk_psicologo_has_pacientes_pacientes1_idx` (`id_pacientes` ASC) VISIBLE,
  INDEX `fk_psicologo_has_pacientes_psicologo_idx` (`id_psicologo` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_psicologo_has_pacientes_psicologo`
    FOREIGN KEY (`id_psicologo`)
    REFERENCES `LaVie`.`psicologo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_psicologo_has_pacientes_pacientes1`
    FOREIGN KEY (`id_pacientes`)
    REFERENCES `LaVie`.`pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
